# Generated by Django 2.0.5 on 2018-09-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('target', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('followings', models.IntegerField()),
            ],
        ),
    ]
