# Generated by Django 2.0.5 on 2019-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190107_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='postsPerDay',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='account',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
