# Generated by Django 2.0.5 on 2019-01-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190108_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='postsPerDay',
        ),
        migrations.RemoveField(
            model_name='account',
            name='timer',
        ),
    ]
