# Generated by Django 2.0.5 on 2019-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190108_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
