# Generated by Django 2.0.5 on 2019-01-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='timer',
        ),
    ]
