# Generated by Django 2.0.5 on 2019-01-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='postsPerDay',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='account',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
